enabled_locales: ["en", "vi"]
learn_enough_web: "https://www.learnenough.com/"
rails: "https://rubyonrails.org/"
rails_book: "https://www.railstutorial.org/book"
rails_contact: "https://www.railstutorial.org/contact"
rails_help: "https://www.railstutorial.org/help"
rails_news: "https://news.railstutorial.org/"
rails_tutorial: "https://www.railstutorial.org/"
screencast_web: "https://screencasts.railstutorial.org/"
author: "https://www.michaelhartl.com/"
max_name_length: 30
min_password_length: 8
max_email_length: 255
email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
avatar_size: 50
item_in_page: 20
